### ISSUE TITLE
Styles not being applied to component using: Pretty (and safe) Pipe

### ISSUE THREAD

**Issue by benwinding** [matiboy/angular2-prettyjson#10]
I've got the pipe working using the [Component Method](https://github.com/matiboy/angular2-prettyjson#component).

However when I'm using the **Pretty (and safe) Pipe**, the custom colors, defined in the css styles are not applied to the html generated by the pipe.

**Component Definition:**
```
@Component({
  selector: 'bom-view-table',
  template: `
     <div>
       <pre [innerHtml]="obj | prettyjson:3"></pre>
     </div>
  `,
  styles: [`
    string { color: green; }
    number { color: darkorange; }
    boolean { color: blue; }
    null { color: magenta; }
    key { color: red; }    
  `]
})
```

**HTML Source:**
![image](https://cloud.githubusercontent.com/assets/11782590/22409973/f776c2c8-e6e1-11e6-9938-f7a8aca71246.png)

**HTML Output**
![image](https://cloud.githubusercontent.com/assets/11782590/22409969/ea1dd468-e6e1-11e6-8ddb-d0018c4628e4.png)

The pipe correctly decorates the HTML with the class keywords, but the css styles from the component aren't applied. Is there something I'm doing wrong?

By the way, this is a very helpful module for debugging, thanks for your efforts!

**Comment by matiboy** [comment]
Hi @benwinding , thank you for opening this issue, and glad you find the module helpful.

It looks like using this:

```
styles: [`
    :host /deep/ .string { color: green; }
    :host /deep/ .number { color: darkorange; }
    :host /deep/ .boolean { color: blue; }
    :host /deep/ .null { color: magenta; }
    :host /deep/ .key { color: red; }
  `]
```
for the styles does the trick

Reference: [/deep/](https://angular.io/docs/ts/latest/guide/component-styles.html#-deep-)

Let me know if it works for you.

**Comment by benwinding** [comment]
Hi @matiboy, thanks for the quick response.

Yes, it's working now! Plus I learnt something new!
Maybe update the readme file to include this :+1: 

Cheers,
Ben
