### ISSUE TITLE
Handle long text

### ISSUE THREAD

**Issue by maxime1992** [matiboy/angular2-prettyjson#11]
While debugging with prettyjson, I noticed that it let long text go outside the limit of the component : 

![image](https://cloud.githubusercontent.com/assets/4950209/22596504/16856096-ea2c-11e6-9caf-8b568b79a3e5.png)

In my opinion it would be nice to add `word-wrap: break-word`

**Comment by matiboy** [comment]
@maxime1992 Thank you for your suggestion.
Used white-space on the spans instead.
Fixed in 2.0.4
