### ISSUE TITLE
AOT broken after upgrade angular and angular-cli

### ISSUE THREAD

**Issue by maxime1992** [matiboy/angular2-prettyjson#12]
# Environment
@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

# Error
`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /home/maxime/Documents/pizza-sync/frontend/node_modules/angular2-prettyjson/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /home/maxime/Documents/pizza-sync/frontend/node_modules/angular2-prettyjson/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /home/maxime/Documents/pizza-sync/frontend/node_modules/angular2-prettyjson/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /home/maxime/Documents/pizza-sync/frontend/node_modules/angular2-prettyjson/node_modules/@angular/core/index.d.ts, resolving symbol PrettyJsonModule in /home/maxime/Documents/pizza-sync/frontend/node_modules/angular2-prettyjson/src/prettyjson.module.d.ts, resolving symbol PrettyJsonModule in /home/maxime/Documents/pizza-sync/frontend/node_modules/angular2-prettyjson/src/prettyjson.module.d.ts`

# Other
Might be related to a previous issue https://github.com/matiboy/angular2-prettyjson/issues/8

**Comment by matiboy** [comment]
Thank you for opening this issue.

Upgraded to `@angular/cli` and no more problem.
Closing for now, please let me know if any problem
