### ISSUE TITLE
Got errors for project based on Angular Quickstart template when npm install angular2-prettyjson

### ISSUE THREAD

**Issue by FunCracker** [matiboy/angular2-prettyjson#13]
+-- UNMET PEER DEPENDENCY @angular/common@2.3.1
+-- UNMET PEER DEPENDENCY @angular/compiler@2.3.1
+-- UNMET PEER DEPENDENCY @angular/core@2.3.1
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.3.1
+-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.3.1
+-- angular2-prettyjson@2.0.3
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-rc.4
`-- UNMET PEER DEPENDENCY zone.js@0.7.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/router@3.2.3 requires a peer of @angular/core@2.2.3 but none was installed.
npm WARN @angular/router@3.2.3 requires a peer of @angular/common@2.2.3 but none was installed.
npm WARN @angular/router@3.2.3 requires a peer of @angular/platform-browser@2.2.3 but none was installed.
npm WARN @angular/router@3.2.3 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN angular2-modal@2.0.0-beta.13 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN angular2-modal@2.0.0-beta.13 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN angular2-modal@2.0.0-beta.13 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN angular2-modal@2.0.0-beta.13 requires a peer of @angular/platform-browser@2.0.0 but none was installed.
npm WARN angular2-modal@2.0.0-beta.13 requires a peer of @angular/platform-browser-dynamic@2.0.0 but none was installed.
npm WARN angular2-modal@2.0.0-beta.13 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN angular2-modal@2.0.0-beta.13 requires a peer of zone.js@^0.6.21 but none was installed.
npm WARN pathruleverifier@0.9.0 No repository field.
npm WARN pathruleverifier@0.9.0 No license field.

**Comment by matiboy** [comment]
Hi, thanks for opening this issue.
I've tried reproducing this with a fresh Angular Quickstart but didn't have any problem.
Most UNMET PEER DEPENDENCY problems seem to point to this
http://stackoverflow.com/questions/35738346/how-to-solve-npm-unmet-peer-dependency

Closing for now
