### ISSUE TITLE
Support angular 4 in dependencies?

### ISSUE THREAD

**Issue by victornoel** [matiboy/angular2-prettyjson#15]
Everything is in the title, I don't think there is API changes that prevent that, it could be great to accept angular from v2 to v4?

**Comment by matiboy** [comment]
Hi there,

Thank you for opening this issue.
I've published 2.0.5 which includes Angular 4 as a valid dependency. Let me know if you encounter any issue

Thanks

**Comment by victornoel** [comment]
seems perfect, thanks :)
