### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by SergeySagan** [matiboy/angular2-prettyjson#17]
I keep getting this error when I try to bundle this in my app (I [REMOVED] stuff that was personal and irrelavant):

```
> browserify -s main  wwwroot/js/main.js > wwwroot/js/bundle.js


C:\Code\[REMOVED]\application\src\[REMOVED]\node_modules\angular2-prettyjson\index.js:1
export { PrettyJsonModule } from "./src/prettyjson.module";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [REMOVED]@1.0.0 browserify: `browserify -s main  wwwroot/js/main.js > wwwroot/js/bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the [REMOVED]@1.0.0 browserify script 'browserify -s main  wwwroot/js/main.js > wwwroot/js/bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the [REMOVED] package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -s main  wwwroot/js/main.js > wwwroot/js/bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs [REMOVED]
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls [REMOVED]
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[REMOVED]\AppData\Roaming\npm-cache\_logs\2017-05-12T05_07_22_762Z-debug.log
```

**Comment by matiboy** [comment]
Hi @Serjster , thank you for opening this issue.

Could you please consider using `babelify` (a browserify transform) which seems to solve this issue for several people. Let me know if that works

Some related issues:
http://stackoverflow.com/questions/37358027/vueify-import-and-export-may-appear-only-with-sourcetype-module
http://stackoverflow.com/questions/41043032/browserify-parseerror-import-and-export-may-appear-only-with-sourcetype

**Comment by SergeySagan** [comment]
Thanks for your quick response. I tried using as you suggested with this command:

> browserify -t [ babelify ]

Actually:

> browserify -t [ babelify ] -s main  wwwroot/js/main.js > wwwroot/js/bundle.js

And I'm still getting the same result.

**Comment by SergeySagan** [comment]
Hey @matiboy I realize this is open-source project so I don't want to hurry you, but I need to know whether you will get a chance to look at resolving this issue soon, or do I need to look at a different option, or can you give me a clue so that maybe I could contribute?

**Comment by matiboy** [comment]
Hi @Serjster 

I'm not able to reproduce the issue actually. Sorry for not clarifying that.
Is your project that you're working on available via some git repo so I could try and run it? I'm not too familiar with `browserify` in all honesty

**Comment by SergeySagan** [comment]
I have company specific stuff in there, any chance that I can google drive share it with your specific google email or some other way without sharing it with the world? Thanks for taking the time.

**Comment by SergeySagan** [comment]
Changed to using Angular via the CLI and it is all working now.

**Comment by matiboy** [comment]
@Serjster Sorry I couldn't be of more help. Glad it worked out in the end
