### ISSUE TITLE
The pipe 'prettyjson' could not be found ("

### ISSUE THREAD

**Issue by phil123456** [matiboy/angular2-prettyjson#18]
Hi,

I added pretty json to my main module but I get the error above

this works:
    <pre [innerHtml]="products | json:4"></pre>

but this does produce the error
    <pre [innerHtml]="products | prettyjson:4"></pre>
```
import {PrettyJsonModule, SafeJsonPipe} from 'angular2-prettyjson';
import {JsonPipe} from '@angular/common';
...
 providers: [
       { provide: JsonPipe, useClass: SafeJsonPipe }
```

do I have to export anything ?

thanks

**Comment by matiboy** [comment]
Hi @phil123456 

> The SafeJsonPipe aims to override the JsonPipe and so uses the same name "json"

If you wish to use the pretty one then you should import `PrettyJsonPipe` instead of `SafeJsonPipe`. The name used by `PrettyJsonPipe` is "prettyjson", whereas SafeJsonPipe's name is "json"

Hope that helps

**Comment by phil123456** [comment]
maybe you should add this to the doc

https://www.npmjs.com/package/angular2-prettyjson

**Comment by phil123456** [comment]
still not working

'prettyjson' is not a known element:

```
import { PrettyJsonModule, PrettyJsonPipe } from 'angular2-prettyjson';
import { JsonPipe } from '@angular/common';.

    providers: [
        ...
        { provide: JsonPipe, useClass: PrettyJsonPipe }
```

since it's used in a submodule, do I have to import it inside of this ? or should it be in app.module ?
sometimes I need to redeclare stuffs in my submodules, dont know why

**Comment by matiboy** [comment]
Are you using the pipe or the component? The pipe is `PrettyJsonPipe` and should work as you did, but you'd need to import the component if you are doing something like `<prettyjson [obj]=...`

Is your project accessible on Github?

**Comment by phil123456** [comment]
I am not too familiar with git, but I created this archive http://ns227325.ovh.net/test-pretttyjson.zip

once I put the imports in a module, (here, the "home" module) it does not work anymore

**Comment by phil123456** [comment]
did you had some time to check it out ?

**Comment by matiboy** [comment]
Hi @phil123456 

I downloaded, npm installed, then I had to `npm install angular2-prettyjson` since it wasnt installed
Adding `PrettyJsonModule` to the imports array in `app.module.ts` worked, like:

```
@NgModule({
  imports: [
    BrowserModule,
    HttpModule,
    FormsModule,
    routing,
    PrettyJsonModule
  ],
...
```

Hope that works for you too

**Comment by phil123456** [comment]
not installed ? did you download the right file ? I have to check that out
it is clearly installed in my project (I just removed the node_modules) and it is clearly giving me an error

**Comment by matiboy** [comment]
It's not in your `package.json`therefore it won't be installed when someone runs `npm install`.
Anyway, after installing and making the change mentioned above, `npm run server` is able to serve it correctly
