### ISSUE TITLE
Not compatible with Angular 2.0.0-rc.4

### ISSUE THREAD

**Issue by steven166** [matiboy/angular2-prettyjson#2]
Hello,
Could you make this module compatible with angular 2.0.0-rc.4?

Thanks in advanced!

**Comment by matiboy** [comment]
Hi,

I've updated the dependencies (to allow above RC1) and the styling.

Do let me know if this works for you

Thanks!

**Comment by steven166** [comment]
Thanks a lot, it fixed my issue :-)
