### ISSUE TITLE
Complie error with Angular 5.1

### ISSUE THREAD

**Issue by tamasfoldi** [matiboy/angular2-prettyjson#24]
Hi,

I've just tried to update my angular to 5.1 and received this error message with cli's prod build:

```
ERROR in Error: Error during template compile of 'PrettyJsonModule'
  Function calls are not supported in decorators in 'NgModule'
    'NgModule' calls a function at @angular/core/core.ts(194,31).
```

Can you fix this it please?

**Comment by matiboy** [comment]
Hi @tamasfoldi Thank you for opening this issue.

I've just created a project with angular 5.1.2 and npm installed angular2-prettyjson (v2.0.6)
All seems to work fine, I even tried compiling it using aot (which seemed related)

Could you please help me reproduce your issue

Thank you

Mat

**Comment by tamasfoldi** [comment]
Hi @matiboy,

Thanks for the response even on Christmas Eve. When I opened the issue I was using angular 5.1.0. On 5.1.2 I neither get the error, maybe there were some issue with the compiler.

Thanks again, and Merry Christmas!

**Comment by ethanve** [comment]
I'm using 5.2 and I only see the error when I enable AOT development compilation. I need to be sure that's the case. Will work on a sample

EDIT: will have to look into it more. Not sure what the cause is

**Comment by matiboy** [comment]
Hi @ethanve 

Thank you, the biggest problem with this issue is that I fail to reproduce it, so if you have any form of sample that would definitely be a big help

Mat
