### ISSUE TITLE
Incompatibility with Angular 5.2.0

### ISSUE THREAD

**Issue by apkd** [matiboy/angular2-prettyjson#26]
The error I'm getting during `ng serve`:
```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular2-prettyjson/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```
Apparently Yarn decided to install Angular twice:

```
apk@apk:~/src/project/node_modules/angular2-prettyjson$ find . -maxdepth 3 -type d -exec ls -d "{}" \;
.
./node_modules
./node_modules/@angular
./node_modules/@angular/core
./src
./dist
```

**Comment by apkd** [comment]
Turns out I had my `@angular/core` version set to `5.2.0` instead of `^5.2.0`. This resulted in Yarn again installing `5.2.1` as an internal dependency. Maybe consider moving `@angular/core` to peerDependencies? For now the issue can be closed, I guess.

**Comment by pfeigl** [comment]
Actually this is driving me crazy :( Whenever I update angular, this library keeps it's own dependency to the old angular version.

Easily fixable by removing and re-installing the library, but it would help so much, if the dependency to angular/core was defined as peerDependency.

Here is an example yarn.lock of the erroneous situation
```
"@angular/core@5.2.3":
  version "5.2.3"
  resolved "https://registry.yarnpkg.com/@angular/core/-/core-5.2.3.tgz#157dcb437d085b325513689e0e4ae70182f3f708"
  dependencies:
    tslib "^1.7.1"

"@angular/core@>=2.0.0":
  version "5.2.2"
  resolved "https://registry.yarnpkg.com/@angular/core/-/core-5.2.2.tgz#54950023b971d9e01f6f6fdbc30d2b68e4d05eb2"
  dependencies:
    tslib "^1.7.1"
```

And this is how it should look like:
```
"@angular/core@5.2.3", "@angular/core@>=2.0.0":
  version "5.2.3"
  resolved "https://registry.yarnpkg.com/@angular/core/-/core-5.2.3.tgz#157dcb437d085b325513689e0e4ae70182f3f708"
  dependencies:
    tslib "^1.7.1"
```

**Comment by matiboy** [comment]
@pfeigl Thanks for your comment. I'm actually working on the build process which should also be able to alert me when AoT breaks; the new version will not have angular as dependency, but as peerDependency as you suggest.

Will keep you posted

**Comment by matiboy** [comment]
Fixed in latest version; please reopen if problem persists
