### ISSUE TITLE
PrettyJsonComponent and SafeJsonPipe not exported

### ISSUE THREAD

**Issue by redrogers** [matiboy/angular2-prettyjson#28]
I'm getting this message when I try to import PrettyJsonComponent in app.component.ts :
 ```[ts] Module '"c:/Users/redro/tree-converter/node_modules/angular2-prettyjson/angular2-prettyjson"' has no exported member 'PrettyJsonComponent'.```

The import statement: ```import { PrettyJsonComponent } from 'angular2-prettyjson';```

This also happens when I try to import SafeJsonPipe in app.module.ts.

Here are my dependencies:
```"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "ajv": "^6.1.1",
    "angular2-prettyjson": "^3.0.1",
    "core-js": "^2.4.1",
    "primeng": "^5.2.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.0",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }```

**Comment by matiboy** [comment]
Hi @redrogers thank you for opening this issue.

The component and the pipes are declared in the module now, so there is no need to import them and declare them. 
I forgot to rewrite the README.

Unless you have the specific need to import one of them, rather than the module?

So basically once you've done `imports : [PrettyJsonModule]` you can use `<prettyjson [obj]="circ">` in any of your components

Please let me know if this works for you

Mat

**Comment by redrogers** [comment]
It worked.  What pretty JSON!  Thank you.
