### ISSUE TITLE
css style not applied, instead literal<span> tags are shown

### ISSUE THREAD

**Issue by Phazzer** [matiboy/angular2-prettyjson#30]
Hello and thanks for the great tool!

Sorry if this question is too stupid to be asked :)

In an angular template I am using string interpolation and the `prettyjson` pipe, intending to show a form value as formatted json:
`{{ form.value | prettyjson }}`
 
However in the browser, instead of the css style being applied, I see the raw html <span> tags. I mean like this:
`<span class="key">"application":</span>` ... and so on.

What can I be doing wrong?

**Comment by matiboy** [comment]
Hi @Phazzer 
No problem asking; I'm a bit out of touch with Angular though.
Which version of Angular are you using, and could you please share some code either here or in a Gist
Thanks

Mat

**Comment by Phazzer** [comment]
Hi and sorry for the long response time. I'm using angular 7. I'm happy, managed to get it to work with this:

 `<prettyjson [obj] = "form.value"></prettyjson>`

... as described in the [instructions](https://github.com/matiboy/angular2-prettyjson#component). 

Best regards!
