### ISSUE TITLE
Angular 2.0.0-FINAL support / modularization

### ISSUE THREAD

**Issue by tdsmithATabc** [matiboy/angular2-prettyjson#5]
In the final release of Angular 2 (technically, as of RC6), you can no longer define pipe dependencies at the component level: (cf. [CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1))

> **[BREAKING CHANGES]** 
> 
> core: previously deprecated @Component.directives and @Component.pipes support was removed.
> 
> All the components and pipes now must be declared via an NgModule. NgModule is the basic compilation block passed into the Angular compiler via Compiler#compileModuleSync or #compileModuleAsync.

As a result, the package throws an error:

> zone.js?fad3:344 Unhandled Promise rejection: Template parse errors:
> The pipe 'prettyjson' could not be found (
> 
> ```
>    <pre [ERROR ->][innerHtml]="obj | prettyjson">
>    </pre>
> ```
> 
>  ): PrettyJsonComponent@1:9

Temporarily users can manually declare the `PrettyJsonPipe` in _their application's_ module's `declarations` array. But the long term solution would be to make this package into a module so it can declare that for itself. (The angular team is pushing package builders towards module encapsulation anyway.)

**Comment by tdsmithATabc** [comment]
FYI, I can probably put a PR together this weekend if you want, but I wanted to document the issue right away. 😉

**Comment by matiboy** [comment]
Hi @tdsmithATabc 
Thanks for opening this issue, and documenting it so thoroughly.
I'd be very happy to take a PR. Thanks for helping out!

**Comment by matiboy** [comment]
@tdsmithATabc Do you think you could have a look at PR #6 ?

**Comment by tdsmithATabc** [comment]
LGTM

While you're at it though, you might want to remove the `rxjs`, `zone.js`, and `@angular/common` dependencies? I don't think you utilize any of those and it'll help combat dependency mismatches in the future. 😉

**Comment by sguiheux** [comment]
Could you now make a release ? :)

**Comment by matiboy** [comment]
Done as v2.0.1
Sorry for the long delay
