### ISSUE TITLE
AOT issue ?

### ISSUE THREAD

**Issue by maxime1992** [matiboy/angular2-prettyjson#8]
Hi !

First of all, let me thank you for this module because it's really helpful for debugging. :+1: 

One thing tho, I'm now using it with angular-cli beta.24 and as soon as I import the `PrettyJsonModule` I get : `ERROR in PrettyJsonModule is not an NgModule`.

I was using your module in beta.22 and I didn't have that problem.
Since AOT checking was enabled by default in beta.23, I think the problem might come from there.

Did you build this module AOT compatible and I'm missing something or is it possible that the module is not yet AOT compatible ?

Cheers !

**Comment by matiboy** [comment]
Hi @maxime1992 ,

Thank you for opening this issue. I will look into AOT and see how that might be messing up with the module.

Mat

**Comment by maxime1992** [comment]
Version 2.0.2 is working great with AOT :smile: 

Thanks for fixing and publishing it so quickly !

**Comment by matiboy** [comment]
Glad it works 👍
