### ISSUE TITLE
Cannot import

### ISSUE THREAD

**Issue by jesse-osiecki** [matiboy/angular2-prettyjson#9]
Can you add correct systemjs.config.js entries to the README? I can't seem to import the library in a sane way.

How do you have it set up in your example?

**Comment by matiboy** [comment]
Hi @stratosmacker 

Thanks for opening this issue.

I personally use [Angular CLI](https://github.com/angular/angular-cli) which uses webpack, and with the steps provided in the README it all works.

I read that the Angular2 quickstart uses SystemJS, is that what you've based your project on?

I will try and install that later and keep you updated

Thanks

Mat

**Comment by jesse-osiecki** [comment]
Yes,

Sorry for the elementary questions, I honestly didn't know how to articulate the difference.

You taught me something new!

**Comment by matiboy** [comment]
Please check whether the UMD bundles that come with v2.0.3 work for you.
My setup on Angular-quickstart is in the updated README

Thanks
